name = "mini-geo-guessr-auth"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
HOSTNAME = "localhost:8787"

# These will be set as secrets in production
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"

[[env.production]]
name = "mini-geo-guessr-auth"
vars = { HOSTNAME = "your-production-domain.com" }

[[env.staging]]
name = "mini-geo-guessr-auth-staging"
vars = { HOSTNAME = "your-staging-domain.com" } 