name = "mini-geo-guessr-auth"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
HOSTNAME = "localhost:8787"

# Load environment variables from .env file for local development
[env]
SUPABASE_URL = "env(SUPABASE_URL)"
SUPABASE_SERVICE_ROLE_KEY = "env(SUPABASE_SERVICE_ROLE_KEY)" 